### ISSUE TITLE
Widevine update check bypass

### ISSUE THREAD

**Issue by Nigel1992** [dut-iptv/dut-iptv#100]
Hi,

Where is the function located that checks for Widevine updates?
The file and line I mean.
It seems to be buggy on the old Leia version and I want to comment the update checking out of the script.

**Comment by dut-iptv** [comment]
It is probably somewhere in base/l6/inputstream.py, but I don't provide support for old versions and you can just run a directory search in Notepad++ or IDE to lookup widvevine/update

Widevine updates are done using Inputstream Adaptive in more recent versions and start from the home function in base/l8/menu.py.
