### ISSUE TITLE
[T Mobile][1.4.2] Playback issue caused by SSL certificate verification failure

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv#102]
Hi!

The T Mobile addon is not working anymore..

I'm getting this error:

![20220123_131837](https://user-images.githubusercontent.com/2340835/150678655-ef126fc0-bbc3-4f66-bdd3-fa9adfaeba97.jpg)

If you need any more info, please let me know.

Cheers and have a nice day!

Marcel

**Comment by dut-iptv** [comment]
The current SSL certificate being used by T-Mobile causes this error.
When testing the certificate using their own SSL provider (DigiCert) on https://www.digicert.com/help/ is shows it is not properly configured. 

Pretty sad for such a major organistation to fail at such a basic configuration.

So the only true solution is for T-Mobile to get their act together at fix the SSL certificate for t-mobiletv.nl

For the time being I have disable SSL verification in the T-mobile addon.
It's a quick fix, but not a good one. Needs to be reverted ASAP but dependant on T-mobile

**Comment by dut-iptv** [comment]
I have created a proper workaround in 1.4.4.

Still rediculous that  this is necessary but at least the problem is solved
