### ISSUE TITLE
[T Mobile ][1.4.4] ONLY NPO 1,2,3 are working

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv#106]
Hi! Another bug report.. Sorry!

Only the NPO channels are working with T Mobile.. The rest is broken..

Cheers,
Marcel

**Comment by dut-iptv** [comment]
Once again this is related to the invalid SSL certificate at T-Mobile.

Have you filled a complaint yet?

**Comment by dut-iptv** [comment]
I have created a workaround once again for this T-Mobile created issue in 1.4.5.

I will not accept any more issues related to the invalid T-Mobile SSL certificate from this point on.
