### ISSUE TITLE
Videoland plugin: Not possible to choose what profile to use

### ISSUE THREAD

**Issue by ns1207** [dut-iptv/dut-iptv#107]
Videoland plugin: Not possible to choose what profile to use
With videoland it is possible to make a profile for each family member, when using this plugin it is not possible to choose which user is watching, it defaults to the first profile.
It would be great to be able to choose a default profile.

**Comment by dut-iptv** [comment]
Profile selection is in the main menu of the addon or have I misunderstood your question?

**Comment by ns1207** [comment]
Sorry, i searched in the plugin settings, i figured it would be there.
But it is working now!
Thanx
