### ISSUE TITLE
RPi 2b+ LibreELEC-RPi2.arm-9.2.8 not supported?

### ISSUE THREAD

**Issue by joostlitjens** [dut-iptv/dut-iptv#109]
Hi mate,
I would love to run your addon, i have got an RPi 2B+ with RPi 2&3 LibreELEC-RPi2.arm-9.2.8.
Librelec 10 is not yet availble.

I installed the addon succesfull only i can't run it.

Could it be it not supported? (i can't do run or configure)
I also don't see it in video addons, but i can see it is in the installed list.

Thanks in advance!

**Comment by hagst** [comment]
LibreELEC 9.2.8 is based on Kodi 18.9.  This addons only supports programs based on Kodi 19.x.
You could look at OSMC (based on Kodi 19.3)  or wait untill there is a LibreELEC 10 version for RPi 2, RPi 3 (currently still too experimental).

**Comment by hagst** [comment]
LibreELEC 9.2.8 is based on Kodi 18.9.  This addons only supports programs based on Kodi 19.x.
You could look at OSMC (based on Kodi 19.3)  or wait untill there is a LibreELEC 10 version for RPi 2, RPi 3 (currently still too experimental).

**Comment by dut-iptv** [comment]
Support for Kodi 18 was removed long ago.

You can see in the README that Kodi 19 is required.
