### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv#11]
Hi,

I'm getting this error while trying to update your addons:

![20210202_192402](https://user-images.githubusercontent.com/2340835/106645164-486f1b80-658c-11eb-96c6-cba70fb8d32b.jpg)

Edit: oh, new update I see.. Now its working!

**Comment by dut-iptv** [comment]
Versioning error in the addon.xml of the proxy part.
Was fixed about the same time you created this issue

**Comment by powermarcel10** [comment]
> Versioning error in the addon.xml of the proxy part.
> Was fixed about the same time you created this issue

Yeah, this was your quickest fix so far! :p
