### ISSUE TITLE
[T mobile][1.4.5] Streams don't play due to SSL certificate verification failure

### ISSUE THREAD

**Issue by hekc0211** [dut-iptv/dut-iptv#110]
**Describe the bug**
streams fail to play and an error relating to the SSL-certificate

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
- Type: [Raspberry pi 4]
 - OS: [LibreElec 10.0.1]
 - Kodi Version [e.g. 19.3.0]
 - Addon Version [e.g. 1.4.5]

**Additional context**
When opening a tv channel i see this window about a problem with SSL
![20220204_182629](https://user-images.githubusercontent.com/99037389/152574723-422623a6-30e5-4432-8cd5-e59ce8a955e8.jpg)

**Comment by dut-iptv** [comment]
This is not a bug, this is a misconfiguration at t-mobiletv.nl.

Issues with the certificate should be directed at T-mobile using their customer service or community forum. You can point them at https://digicert.com/help which shows their Digicert SSL certificate for T-mobiletv.nl is misconfigured.

As stated before in #102 and #106 I will not be accepting any more issues for a problem that is entirely of T-Mobiles making and their inability to get even the most basic web server configuration right.
