### ISSUE TITLE
ziggo, nothing plays.  IPtv error

### ISSUE THREAD

**Issue by kersvanbinsbergen** [dut-iptv/dut-iptv#113]
![IMG_20220208_134045](https://user-images.githubusercontent.com/35664088/152989314-c2cbdf11-6242-44e5-b76d-b932d81833c3.jpg)

Hi,

To be sure i updated IPtv, but the error still exists.

Does anyone has an idea what's going on?

**Comment by dut-iptv** [comment]
Follow the issue guidelines when posting an issue.
Be expletive about your problem, what is your issue, when does it occur etc.

The issue template is there for a reason.
Failure to adhere to the template will lead to immediate closure of your issue
