### ISSUE TITLE
[ZIGGO][1.4.4] nothing plays

### ISSUE THREAD

**Issue by kersvanbinsbergen** [dut-iptv/dut-iptv#114]
**Describe the bug**
Anything i click live, replay,  won't start

**To Reproduce**
1. Go to '...' addons
2. Click on '....' ziggo
3. Scroll down to  replay,  select show
4. See error image

**Expected behavior**
Start show

**Screenshots**

![IMG_20220208_134045](https://user-images.githubusercontent.com/35664088/153063876-20977866-8dea-4e48-985a-4604dd82ec25.jpg)

**Device (please complete the following information):**
- Type:  Android TV Box mibox 4
 - OS: Android 9.0.0.0 API 28 Linux 4.9,113
 - Kodi Version 19.3
 - Addon Version anon 1.4.4+matrix.1

**Additional context**
Pvr iptv nightik and Ross nickelson 19.1.0

**Comment by dut-iptv** [comment]
Thanks for taking the time to provide some more information.

I quickly tested Ziggo Live and replay playback on Kodi 19.3 running on my android phone and found no issues. So there does not seem to be a general issue with Ziggo playback.

The image of the log you provided does not show any errors related to my addons. The Simple IPTV (note: not my addon) errors do suggest a general connectivity failure. Are you sure the Mi box and Kodi are able to connect to the internet? Does something like the Kodi South Park or Youtube addon function without issues?

If other addons don't have any internet access issues you can try a session reset or updating your login information to forcefully recreate a Ziggo session and than try again.

**Comment by kersvanbinsbergen** [comment]
Hi, thanks for checking mate.

Yesterday i  updated my login credentials again to make sure there is a connection.   ( for your information: i did change my password and few weeks back)

Maybe i need to reinstall kodi and your plug in.  No problem.  I'll keep you posted but i don't know when

**Comment by kersvanbinsbergen** [comment]
:-) installing was easier than i remembered .

Unfortunately it doesn't work but i do get error from your genius plugin now.

![IMG_20220209_165630](https://user-images.githubusercontent.com/35664088/153239120-5618a8ec-3646-44f2-b62b-32278b0bacfb.jpg)

**Comment by kersvanbinsbergen** [comment]
Reset cache,  reset add-on,  install dut-IPTV Simpele IPTV Connector.

Live and replay TV are playing now except that one (7-feb-22)  episode of VI vandaag
