### ISSUE TITLE
[CanalDigitaal] Screen freezes after a few seconds

### ISSUE THREAD

**Issue by Underlyingglitch** [dut-iptv/dut-iptv#123]
When watching a stream with Canal Digitaal the video stream freezes every couple of seconds, or seems to play in slow motion (almost as if it is buffering)

Network is not being used by anything else, so the kodi device should have the full 100Mbit/s download speed available. 

Never had this issue with the Ziggo plug-in. 

Also doesn’t matter if I’m watching Live TV or Replay TV.

**Comment by dut-iptv** [comment]
What device?, what OS?, Have you tried another OS?

This is why there is an Issue Template and why issues that don't follow the Template are closed.
