### ISSUE TITLE
[T-mobile] Support for T-mobile TV IPTV

### ISSUE THREAD

**Issue by stoked-security** [dut-iptv/dut-iptv#127]
I'm not sure if you are aware, but next to T-mobile Go there is also an Android app called T-mobile TV. This is an app that is supposed to run on an Android TV device. The idea is that this will replace the hardware settop box (Amino) that is supplied by T-mobile. As you may know the back end IPTV system the settop box uses is different from what the T-Mobile Go app uses and seems to be higher quality. The same is most likely true for the T-mobile TV Android app.

As I don't own an Android TV myself, I tried to get a hold of the APK file and started experimenting a bit with Android Studio and the emulator it provides. I succeeded in running the T-mobile TV app in the emulator and could login and watch TV. However, only channel 1 till 3 would work for some reason, maybe due to the other channels using Widevine encryption?. By defining a HTTP proxy in Android Studio I managed to intercept the HTTPS network traffic with Burp Suite. In other words I'm able to man in the middle the HTTPS connection and see all HTTP requests to the back end systems. This is probably a good starting point to reverse engineer how the app works and implement this in dut-iptv. 

Would you be interested in working together to try to implement this IPTV back end into dut-iptv? I can provide a lot more detail like the APK itself, instructions on how to setup the emulator and proxy. What I'm lacking at the moment is a detailed understanding of how dut-iptv is structured and how support for a new back end should be added. Looking forward to your response.

**Comment by dut-iptv** [comment]
All information available to me points to the new IPTV platform on Amino boxes, the Android TV app, the Android app and my addon al using the same backend and stream quality. All have a maximum quality of 1080p60 with a max stream bitrate of about 6 Mbit.

So I don't believe this is something that will improve the quality of the addon. If you have a source from (the) T-Mobile (forum) that can show some way of playing T-Mobile streams in a higher quality we can have a look at this.

**Comment by stoked-security** [comment]
Hi, just to give you an update. I've just done a side to side comparison between dut-iptv, the Amino hardware set top box and the Android TV app running in the emulator. When watching sports like tennis (Roland Garros at the moment) or soccer (Be-NL) you can see a clear difference in quality of the streams. For both the set top box and the Android TV fast ball movements look a lot smoother, as if they are running at a higher frame rate compared to dut-iptv stream. Also the overall image is calmer and easier on the eye. I'm running dut-iptv on a fresh install of LibreElec on RPi4 hardware, so that should not be the cause of the difference.

Also I noticed that both dut-iptv and the T-mobile Anywhere app have only one Eurosport channel instead of two for the set top box and Android TV app. The Android TV app is using a different back end systems compared to dut-iptv:
https://eds.prd.tv.t-mobilethuis.nl:443/
https://vsc01.prd.tv.t-mobilethuis.nl:443/

Let me know if you require any additional information or testing. Looking forward to your response.
