### ISSUE TITLE
Toevoeging uitzending gemist

### ISSUE THREAD

**Issue by dkoek** [dut-iptv/dut-iptv#13]
In onderstaande github thread een werkende NOS uitzending gemist add-on:

https://github.com/Opvolger/plugin.video.uzg

Toevoegen ?

**Comment by dut-iptv** [comment]
A. Please always post in English

B. This repo is not a collection of all known addons that provide access to Dutch/Belgium broadcasting or VOD services. This repo is for addons that I have developed myself for IPTV/VOD services that don't have a known addon in existance or where current addons in Kodi are lacking in functionality (in my opinion). I will not be including addons of other developers here. 

Ask Opvolger to provide a Kodi repo if he does not do so already or just download updates manually

Or just use Retrospect which is available from the official Kodi repository and not only includes NPO but also RTL and SBS
