### ISSUE TITLE
Videoland LEIA support coming ?

### ISSUE THREAD

**Issue by Nigel1992** [dut-iptv/dut-iptv#14]
If so, any ETA ?

**Comment by dut-iptv** [comment]
I halted Leia development at 1.0.0. 
Support for python 2 / Kodi 18 workarounds was removed in 1.0.1. 
Videoland was based on 1.0.5.

So it's not planned.

Kodi 19 RC1 was released a month ago.
From RC1 to final for 17 and 18 took about 2 months.
So hopefully 19 final will be available in about a month.

**Comment by Nigel1992** [comment]
Ok. Thanks for your comment.
I will wait for LibreELEC to update to matrix, aswell for the addons I use.
