### ISSUE TITLE
nlziet Extra zender pakket bij live tv

### ISSUE THREAD

**Issue by yaelruhl** [dut-iptv/dut-iptv#140]
Nlziet Extra zender pakket niet zichtbaar bij Live TV

https://www.nlziet.nl/nl/blog/nlziet-extra/

**Comment by g4hammer** [comment]
Long story short, as far as I could understand all code for this plugin, the extra channels are missing here: https://github.com/dut-epg/dut-epg.github.io/blob/master/nlziet/channels.json

**Comment by yaelruhl** [comment]
yes that is the problem

**Comment by yadzio** [comment]
I have been using this kodi addon for some time now and was very happy with it. It still works fine without the extra channels. I am not a technical person, so I can't help to write that code. Is anyone working on that who has the knowledge? Happy to contribute in any way I can e.g. testing. I have a subscription to the extra channel tier.

**Comment by yaelruhl** [comment]
# @dut-sees

do you know how to add the extra channels?
your version with the fixes from yesterday is working great so i thought aksing you

**Comment by yaelruhl** [comment]
@dut-sees

the channels are working now

can you get the Simple IPTV Connector working again?
that would be great
