### ISSUE TITLE
[Videoland] Add live TV, categories, continue watching, profiles and sort options

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv#17]
Hi,

For Videoland; 

1) Is it possible to add the other categories like recently added, most watched, Dutch Series, etc? 

2) The addon sorts evertything alpabaticly. In the android videoland app, it doesnt. Is this something you can change?

**Comment by dut-iptv** [comment]
I might think about adding number 1 in a future versions, but it is not a priority.

Number 2 will not be added

**Comment by dut-iptv** [comment]
Continue watching and profiles added to requests that might be worked on in the future as requested in #27 and #28

**Comment by djdirty60** [comment]
Do these features already work?

**Comment by dut-iptv** [comment]
I don't have a Videoland subscription right now, but will renew shortly and have a look at implementing a few new features.

Per @powermarcel10 request will also look into adding live channels

**Comment by dut-iptv** [comment]
Videoland live channels (Darts + RTL 4/5/7/8) will be in 1.2.8

**Comment by powermarcel10** [comment]
> Videoland live channels (Darts + RTL 4/5/7/8) will be in 1.2.8

That's great!!

**Comment by dut-iptv** [comment]
Profile support will be in 1.2.8

**Comment by djdirty60** [comment]
Thnx

**Comment by dut-iptv** [comment]
Continue watching support will be in 1.2.8

**Comment by dut-iptv** [comment]
Categories such as recently added, most watched, Dutch Series will be in 1.2.8

**Comment by djdirty60** [comment]
Is it possible if you have watched something in Continue Watching that it will leave as viewed?

And that recently added by adding date is instead Alphabetical?

**Comment by dut-iptv** [comment]
@djdirty60 

I will cover sorting options in #81.

Leaving items in Continue watching is not possible as this view gets its information directly from Videoland. If you watch something completely it will disappear from continue watching on the website and thus from Kodi. I might be able to implement something to mark items that you have watched in other places (like mark episodes you have watched on other devices/apss as watched in series) but this is not a priority. A separate issue with this request should be made as this issue already contains way too much different features already.

If no issues are found I will close this in a week

**Comment by djdirty60** [comment]
> @djdirty60
> 
> I will cover sorting options in #81.
> 
> Leaving items in Continue watching is not possible as this view gets its information directly from Videoland. If you watch something completely it will disappear from continue watching on the website and thus from Kodi. I might be able to implement something to mark items that you have watched in other places (like mark episodes you have watched on other devices/apss as watched in series) but this is not a priority. A separate issue with this request should be made as this issue already contains way too much different features already.
> 
> If no issues are found I will close this in a week

I mean actually from the videoland app to the kodi addon, it removes the watched episode.  but not from the addon to the app.  that's why it probably also remains visible in the addon as not viewed

**Comment by powermarcel10** [comment]
Hi, thanks for the update! Live TV is not working yet.. There are no items in this folder. Any idea?

**Comment by dut-iptv** [comment]
Live TV worked but disappeared because of a misconfiguration on the EPG side. Should pop up again without updates to the addon. Please note that RTL darts link does not work at this time because the stream is not live and it does need manual updating when the stream is Live again. Please notify me when it does (and it does not already work at that time).

**Comment by dut-iptv** [comment]
@djdirty60 

The next version should handle pushing the last play time from Kodi to Videoland correctly.

**Comment by djdirty60** [comment]
> @djdirty60
> 
> The next version should handle pushing the last play time from Kodi to Videoland correctly.

Thnx 👍

**Comment by dut-iptv** [comment]
1.3.0 with proper support for pushing the last play time from Kodi to Videoland is now in the repo

**Comment by dut-iptv** [comment]
I will close this issue as I do believe all enhancements in this issue specific to Videoland have been included. As said before sorting will be covered in issue #81
