### ISSUE TITLE
[T-MOBILE][1.0.8] No surround sound anymore

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv#18]
Hi,

Since a couple of days I'm not having surround sound (dolby digital) using T-Mobile anymore.. I cannot remember since wich version of the addon this started.. Has there something been changed?

**Comment by dut-iptv** [comment]
There is still surround, but I might not be selected by default anymore. After some investigating both this and #16 might be related to the modifications done by the proxy to the MPD file which for some reason fail on android/Chromebook. Will need to investigate further

**Comment by powermarcel10** [comment]
Aaaah alright, thanks for your reply. I have selected the force surround option enabled btw.

**Comment by powermarcel10** [comment]
Hi Any news on this one? Is it worth to try a previous version of the proxy addon in order to fix it? Or will this break other things..

**Comment by dut-iptv** [comment]
Fixed in 1.0.9, will be up in a few hours

**Comment by powermarcel10** [comment]
For T Mobile it's fixed now! Thanks. Only Videoland also has no surround sound.. Should I make a new issue here on github?

**Comment by powermarcel10** [comment]
No option to add dolby to videoland?
