### ISSUE TITLE
[All] Support for UpNext addon

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv#19]
Hi!

I would like to ask for support for the UpNext addon:

https://forum.kodi.tv/showthread.php?tid=336747

Its allready compatible for kodi 19 and availible in the kodi repo. Netflix and some other addons are allready working with it. 

This way the next episode of a serie will play automatically and you get a popup when the current episode is almost finished. Like Netflix does.

**Comment by dut-iptv** [comment]
Will look into adding it for 1.10

**Comment by dut-iptv** [comment]
UpNext integration for NLZiet and Videoland is currently being tested and probably will be released in the coming weeks.

It will for the time being only be implemented for TV Shows that are being played from your library using the library integration for these two addons (being discussed in #84).

**Comment by dut-iptv** [comment]
UpNext integration for NLZiet and Videoland is included in 1.4.2 which is in the main repo now.
This is a preliminary implemantation that is by no means perfect and will probably be modified in the upcoming releases. It also only works for items included in your library.
