### ISSUE TITLE
[Ziggo][1.0.8] Movies and Series throw error

### ISSUE THREAD

**Issue by atreyuhere** [dut-iptv/dut-iptv#20]
I noticed when selecting a(ny) movie or series an error is thrown.

TypeError: api_get_vod_by_type() missing1 requirement positional argument: 'genre'

File "/resource/lib/api.py", line 644, in api_vod_seasons

**Comment by dut-iptv** [comment]
Should be fixed in 1.0.9, will be up in a few hours
