### ISSUE TITLE
[All][1.0.8] "Ask to start stream from beginning" does not work

### ISSUE THREAD

**Issue by denniedegroot** [dut-iptv/dut-iptv#23]
**Describe the bug**
The option "Ask to start stream from beginning" does not work and throws an error.

**To Reproduce**
Enable the option "Ask to start stream from beginning" and start watching a channel.

**Expected behavior**
Confirmation box if I want to start from the beginning

**Screenshots**
![Schermafbeelding 2021-02-25 om 19 03 35](https://user-images.githubusercontent.com/662966/109196804-7830ce00-779c-11eb-80f0-b768d1645ad8.png)

**Device (please complete the following information):**

**Additional context**

**Comment by dut-iptv** [comment]
Fixed in 1.0.9, will be up in a few hours
