### ISSUE TITLE
[Ziggo][1.0.8] Max number of simultaneous viewers reached

### ISSUE THREAD

**Issue by atreyuhere** [dut-iptv/dut-iptv#24]
**Describe the bug**
Ziggo offers 3 simultaneous sessions at the same time.

When using the Ziggo Go Kodi addon, every session that starts after starting a stream in the addon will return 'max reached' on any device (including the active one).

If Ziggo Go streams are started through the Android App or website, three simultaneous session limit is honored.
I believe this issue is causing a number of related issues (switching channel while watching a stream ends the stream in most cases, throwing the user back in the UI. A consequent stream starts immediately if no stream is already running. Starting an archived stream will stall often in teh same way, starting the same archive with no stream running always succeeds).

**To Reproduce**
1. Start a channel 
2. Start another channel while the first one is running
3. Stream will sometimes change/run, but more often the stream stops and user is thrown back to GUI
4. ' The maximum number of streams has been reached' is shown on any device when stream is started.

**Expected behavior**
2 slots should be available when one is running, switching channels should not encounter the max session state and stop the stream.

**Device (please complete the following information):**
- Type: Odroid N2, C4, NUC
 - OS: Coreleec, Windows
 - Browser any browser will behave correctly
 - Version any

**Comment by dut-iptv** [comment]
I forgot if you were on Ziggo V3/V4 (Next box owner)

I can't reproduce your issue on V2, so it might be specific to Ziggo V2.
A mechanism was introduced a couple of versions ago to prevent stale sessions, but this might only work on V2.

If you are on V3 please let me know and I will post some instructions for Chrome so we can find out how streams are ended on V3 in the regular web app.

**Comment by atreyuhere** [comment]
I do not know how to find out which version i am using.
However, i am not using any Ziggo box (next or other), does that put me in the V3 group?

I f you provide me instructions i will carry them out to get the required info.

**Comment by dut-iptv** [comment]
I am still unable to reproduce your issue in the latest version (1.1.1).

I can switch between lots (>8 in a minute) of different live streams without issue through the addon and through the Simple IPTV addon. This was done without stopping playback betweens switching streams.

V2/V3/V4 differences have been removed as of 1.1.1 (as Ziggo seems to have deprecated the V2/V3 login) so there should be no difference between accounts anymore.

**Comment by atreyuhere** [comment]
I have tried in the new version and the stop stream-max sessions issue is still present as it has in every version of the addon.

Since I use several backends, i will try using only the Ziggo Go addon and remove others to see if the issue persists.

**Comment by dut-iptv** [comment]
I do see more errors when I'm running a stream from a browser on ziggogo.tv (which continues without problems) + running a stream from Kodi and switching channels in Kodi. 

I am testing some things in 1.1.2 that seem to resolve the issue and I am able to run a stream on a phone, in the browser and switch channels in Kodi without issue.

**Comment by atreyuhere** [comment]
I am ready to test once you are ready :-)

**Comment by dut-iptv** [comment]
1.1.2 is already in the repo. Please try to launch 2 streams on officially supported platforms (ziggogo.tv and/or official android/ios app) and then start a stream from the addon and try to change channels without stopping playback in between. Try the same using Simple IPTV

**Comment by atreyuhere** [comment]
I installed v 1.1.2 and did some tests.
Started one stream in a browser,logged into the Ziggo go android app and started a stream.
Opened the channel list in kodi (simple iptv). Started a channel. Stream starts normally.

When switching channels in iptv simple, i tried for a good number of channels to reproduce the 'thrown back to GUI' issue but could not. I never stops the stream and mostly changes shrink seconds. 
Sometimes though (haven't noticed a pattern yet) after changing the channel, the current stream will :

- continue playing for 4-5 seconds, then
- current playing channel slows down, then freezes
- after 5-10 seconds after freeze of the current channel, the channel changes to the selected one 

Tried stopping all channels, than starting a channel through Ziggo Kodi addon or simpletv.
Now starting s channel on Ziggo Go on Android or website will start. It never shows the max streams reached message.

I'd say this is a major step forward, as stream limit seems ok now and it doesn't stop the stream anymore. Great work!

**Comment by dut-iptv** [comment]
Seems pretty much fixed then.

The sometimes slow switch could be related to Ziggo or to you exactly switching streams while the current stream is updating the token (every 60s in the Ziggo addon) which might block changing the stream for a short while. Not much I can do on this at the moment.

Suggest you close this.

**Comment by atreyuhere** [comment]
Thank you for looking i to this and significant improvements! Appreciated!
