### ISSUE TITLE
[Ziggo][V3/V4][1.0.9] Starting any stream results in error ' SharedProfileID'

### ISSUE THREAD

**Issue by atreyuhere** [dut-iptv/dut-iptv#25]
**Describe the bug**
Starting a(ny) channel returns an error: KeyError 'sharedProfileId'

**To Reproduce**
1. Start a channel
2. Error is thrown

**Expected behavior**
Channel should start playing.

**Comment by Smultie** [comment]
Same here.
Some extra info:

021-03-03 12:50:34.912 T:695      INFO <general>: CPythonInvoker(3, /storage/.kodi/addons/plugin.video.ziggo/default.py): script successfully run
2021-03-03 12:50:36.269 T:695      INFO <general>: initializing python engine.
2021-03-03 12:50:37.956 T:695     ERROR <general>: plugin.video.ziggo - 'sharedProfileId'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l5/signals.py", line 29, in throwable
                                                       yield
                                                     File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l6/router.py", line 84, in dispatch
                                                       function(**params)
                                                     File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l7/plugin.py", line 28, in decorated_function
                                                       item = f(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l8/menu.py", line 705, in play_video
                                                       playdata = api_play_url(type=type, channel=channel, id=id, video_data=data, from_beginning=from_beginning, pvr=pvr)
                                                     File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/api.py", line 276, in api_play_url
                                                       if not api_get_session():
                                                     File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/api.py", line 137, in api_get_session
                                                       login_result = api_login()
                                                     File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/api.py", line 259, in api_login
                                                       ziggo_profile_id = data['customer']['sharedProfileId']
                                                   KeyError: 'sharedProfileId'

**Comment by dvdevil** [comment]
Running windows 10????

**Comment by Smultie** [comment]
No. I'm running libreelec on a RPi3

**Comment by atreyuhere** [comment]
Coreelec here. I can test on Windows but my expectation is results will be the same.

**Comment by atreyuhere** [comment]
Tested on Windows10.
During first login, same error is shown.

**Comment by tlandman** [comment]
Same here on Nvidia shield. 
![Uploading IMG_20210304_125030.jpg…]()

**Comment by Smultie** [comment]
Your picture is not working @tlandman

**Comment by tlandman** [comment]
> Your picture is not working @tlandman
![IMG_20210304_125030](https://user-images.githubusercontent.com/22493026/110093560-26d79e80-7d9b-11eb-99a0-4085f8cf4b62.jpg)

How about now?

**Comment by Smultie** [comment]
Yup!

**Comment by somrandomMF** [comment]
![troubles](https://user-images.githubusercontent.com/80103790/110111226-4927e700-7db0-11eb-8ed7-3eb5fe4f4d1e.png)

Same here :-(

**Comment by dut-iptv** [comment]
A quick-and-dirty fix for this bug has been uploaded in 1.1.0.
Ziggo has made changes to the login flow which introduced this bug.

As the V2 login flow seems to have been deprecated and all accounts moved to V3/4 login flow I am now able to better debug login issues for all Ziggo users and a better fix will follow in the near future

**Comment by Smultie** [comment]
And it works \0/
Thanks a lot!

**Comment by dvdevil** [comment]
Thank you are the best

**Comment by dvdevil** [comment]
> And it works \0/
> Thanks a lot!
on windows 10?

**Comment by Smultie** [comment]
> > And it works \0/
> > Thanks a lot!
> > on windows 10?

RPi3 with Libreelec in my case

**Comment by atreyuhere** [comment]
Yes, i tried the 1.1.0 version, uninstalled prev. Version completely. Channels play again. Nice!

After login movies and Series get disabled. Don't care much,just reporting ;) 

Another thing I noticed is that if load default channels only and regional channels are disabled, channel selection ignores these parameters.

I understand there have been some changes. Can't wat what you are going to cook up in the bear future. I am very thankful!

Cheers!

**Comment by dvdevil** [comment]
Where can i download this 1.1.0 version ?

**Comment by atreyuhere** [comment]
You can get it from github / dutch iptv repo.

**Comment by dvdevil** [comment]
Yes but only 1.0.9 is listed....

**Comment by atreyuhere** [comment]
It's there, i used it. You might have to select update on the repo

**Comment by dvdevil** [comment]
Are you running windows 10?

**Comment by Smultie** [comment]
that has nothing to do with it

> Are you running windows 10?

**Comment by dvdevil** [comment]
> that has nothing to do with it
> 
> > Are you running windows 10?

Smultie i dot not asking you.....

**Comment by Smultie** [comment]
> > that has nothing to do with it
> > > Are you running windows 10?
> 
> Smultie i dot not asking you.....

You might wanna quote someone to make sure.
Also, it doesn't matter if ppl are running windows 10. This problem was amongst all OSes

**Comment by dvdevil** [comment]
This is why see screenshot
![Naamloos](https://user-images.githubusercontent.com/79605796/110204437-3fb38300-7e73-11eb-8c3e-829bd5a88eb0.jpg)

**Comment by Smultie** [comment]
So... have you checked the log like the message suggests? 
Also, this seems to be a different issue.

**Comment by dvdevil** [comment]
Opened  a post 10 days ago before the shared id error on github....

**Comment by Smultie** [comment]
But... what does the log say?

> Opened a post 10 days ago before the shared id error on github....

**Comment by dvdevil** [comment]
log already posted   [Ziggo][1.0.8] Playback error #21

**Comment by somrandomMF** [comment]
I can see v1.1.0 for matrix, i have leia...

**Comment by dvdevil** [comment]
not for leia

**Comment by somrandomMF** [comment]
Ok but i also have the issue in leia. Just wait for new release in "the near future" then?

**Comment by atreyuhere** [comment]
Development for Leia is halted as far as i know.
So id in teh hear future you install Matrix the answer is yes.

**Comment by chielmi** [comment]
I can't figure out how to update the Ziggo add-on, as I'm also having the SharedProfileID error.
The Dutch IPTV Repository is version 1.1.0, but the Ziggo addon remains on version 1.0.0.

When attempting to update the Ziggo GO add-on I can only choose version 1.0.0. What am I missing 🤔

**Comment by Smultie** [comment]
> Development for Leia is halted as far as i know.
> So if in the near future you install Matrix the answer is yes.

But also: Matrix isn't officially supported on a lot of platforms, RPi included, so I think a large population of the users of this add-ons would very much welcome an update for Leia as well

**Comment by atreyuhere** [comment]
Yes, well. Let's hope the dev finds the time to support obsolete versions. I would definitely understand if he does not.

**Comment by dut-iptv** [comment]
As stated in every readme on this repository: Leia supported ended at 1.0.0 and will not be resumed.

For those staying on a deprecated platform can quick fix this themselves by changing line 291-293 in resources/lib/api.py from:

```
    if int(profile_settings['v3']) == 1:
        ziggo_profile_id = data['customer']['sharedProfileId']
        household_id = data['customer']['householdId']
```

to:

```   
    if int(profile_settings['v3']) == 1:
        try:
            ziggo_profile_id = data['customer']['sharedProfileId']
        except:
            pass
        
        try:
            household_id = data['customer']['householdId']
        except:
            pass
```

As this error is solved in supported versions this issue will be closed in the upcoming days

**Comment by Smultie** [comment]
That still gives an error.

Well, guess I'll have to wait till libreelec updates to Kodi Matrix

**Comment by Smultie** [comment]
Looks like it doesn't like the first line with 

> try:

**Comment by dvdevil** [comment]
Only getting one channel and thats te porn channel rest stays empty (kodi matrix windows 10)

**Comment by dvdevil** [comment]
Any tool to open the lib?

**Comment by dut-iptv** [comment]
@dvdevil Should be fixed. 

Please delete channels.json from your Kodi userdata/addon_data/plugin.video.ziggo/cache directory and try again

**Comment by dvdevil** [comment]
No succes deleted the channels.json....
![Naamloos](https://user-images.githubusercontent.com/79605796/111039233-402cba80-842d-11eb-95bb-5fc40b3ce7c9.jpg)

**Comment by tlandman** [comment]
I have the same issue on shield with matrix and the latest version. See pictures attached with the log. Quick and dirty. 
![IMG_20210313_195207](https://user-images.githubusercontent.com/22493026/111040993-4d01dc00-8436-11eb-9f15-034e93d5e653.jpg)
![IMG_20210313_195152](https://user-images.githubusercontent.com/22493026/111040995-4ecb9f80-8436-11eb-8996-5a4cd1272048.jpg)
![IMG_20210313_195139](https://user-images.githubusercontent.com/22493026/111040998-4ffccc80-8436-11eb-9e43-7e5c557f6d85.jpg)

**Comment by dut-iptv** [comment]
@dvdevil @tlandman Your playback issue is unrelated to the issue mentioned in this thread. Please continue discussion in #21 

This issue related to the SharedProfileID will be closed, as it is fixed in the supported versions.
