### ISSUE TITLE
[ZIGGO][LEIA] Unable to logon

### ISSUE THREAD

**Issue by roksrini** [dut-iptv/dut-iptv#30]
**Describe the bug**
In Kodi 18.9 I cannot login anymore. This happens on old installations as well as after a new Kodi 18.9 installation.

**To Reproduce**
In Ziggo Go addon
1. Go to 'Wijzig Login gegevens'
2. Provide the user credentials
3. I get error (see text below or screenshot):

KeyError:'sharedProfileId'

File "/resources/lib/api.py", line 292, in api_login
 ziggo_profile_id = data['customer']['sharedPtofileId']
File "resources/lib/base/I8/menu.py", line 72, in  login
 login_result = api_login()
File "resources/lib/base/I7/plugin.py", line 34, in decorated_function
 item=f(*args, **kwargs)
File "resources/lib/base/I6/router.py", line 94, in dispatch
 function(**params)
File "resources/lib/base/I5/signals.py", line 29, in throwable
 yield

**Expected behavior**
I should get the message that login was succesful.

**Screenshots**
![ZiggoGo_Error](https://user-images.githubusercontent.com/73710718/111071117-f0a1c980-84d4-11eb-8520-850c60c985b6.jpg)

**Device (please complete the following information):**
- All of these: Android TV Box / PC / Smartphone

**Additional context**
In Kodi 19.1 the login goes well, but there the EPG data is missing in the IPTV Simple Client.

**Comment by SgtHavoc** [comment]
Can confirm.

**Comment by dut-iptv** [comment]
Leia is unsupported since 1.0.0.

If providers change things that break login/playback I won't be fixing them.

Ziggo has done this recently, which is a shame, but this means you will not be able to use the addon in Leia.

Closing
