### ISSUE TITLE
[Ziggo GO][1.0.0 kor Kodi 18 (Leia) on Raspbian Buster and other Raspberry PI] Shared Profile Id issue on setup and playback 

### ISSUE THREAD

**Issue by japywheel** [dut-iptv/dut-iptv#31]
**Describe the bug**
When entering username and password an Unexpected Error is raised. Sam or similar for Matrix, however matrix version now works

**To Reproduce**
1. latest raspberry Pi Os with all updates
2. kodi install from repository 
3. download and install anon repository zip
4. install Ziggo Go Addon 
5. login to Ziggo  Go

**Additional context**
Same issue happened in Kodi 19 (Kodi 19 is not support on vanilla Buster Raspberry Pi OsS

**Comment by dut-iptv** [comment]
Leia is unsupported since 1.0.0.

If providers change things that break login/playback I won't be fixing them.

Ziggo has done this recently, which is a shame, but this means you will not be able to use the addon in Leia.

Closing
