### ISSUE TITLE
[Ziggo] Update of Leia version

### ISSUE THREAD

**Issue by alannl** [dut-iptv/dut-iptv#33]
Hi,,
Kodi 18 Leia still uses the old version of Ziggo GO using API v2, which isn't being used anymore and gives errors.
Could you please update this version?

**Comment by alannl** [comment]
Thanks for your reply, I found your topic with the same error. I won't upgrade to K19 until coreelec updates itself with a functional imiage.

**Comment by atreyuhere** [comment]
I understand; Matrix is not for everyone (yet)

**Comment by dut-iptv** [comment]
Coreelec stable has moved to matrix. There will probably not be a automatic update but if you are on an coreelec-ng build you should be able to upgrade without a clean install by placing the update tar in the .update directory of your device.

As stated Leia development has ended.
