### ISSUE TITLE
[ZIGGO][1.0.0] Not working "No Items"

### ISSUE THREAD

**Issue by SmashRocket** [dut-iptv/dut-iptv#36]
**Describe the bug**
Running a Rasberry Pi box with LibreElec (Leia) that forces me to use 1.0.0. That version isn't showing any channels or programs when logged in. Seems that one isn't being update anymore because Kodi 19 (Matrix) is running fine with the Ziggo (Matrix) addon on my PC and that one is being regularly updated. Would be great if you could give the Leia release some love and include some of those fixes. Matrix is the future but still on Alpha on the Raspberry Pi.

**Comment by dut-iptv** [comment]
Matrix is not the future, it's the present. Leia is the past.

This has been discussed multiple times and I have been very clear that Leia will not be supported any further.

Stop asking.

Closing

**Comment by SmashRocket** [comment]
Ok thanks. It's on your mainpage, support for Kodi 18, so that's outdated now. You should disable/remove the addon and don't give advice to users to start using libreelec (Matrix is Alpha) if you will no longer support it (https://github.com/dut-iptv/dut-iptv/issues/29). Thanks for your efforts uptil now! Was a great addon for the rpi4 users.
