### ISSUE TITLE
[Ziggo][1.0.0] Unexpected Error

### ISSUE THREAD

**Issue by Ankh-** [dut-iptv/dut-iptv#37]
**Describe the bug**
When setting up login information, the add-on gives a unexpected error. See attached screenshot.

**To Reproduce**
Reset login and fill in the username and password. Same error message

**Expected behavior**
Should work. Triple checked with ziggogo.tv on browser and same credentials.

**Screenshots**
![IMG_3720](https://user-images.githubusercontent.com/1950285/114439170-fc160c80-9bc8-11eb-9125-38ab0d04b7b6.jpeg)

**Device (please complete the following information):**
OSMC Vero 4k+

**Additional context**
The password has a " #" character, maybe there is an issue? Also, I am using the addon on a non-ziggo connection. But as said, I can use the login on a webbrowser.

**Comment by atreyuhere** [comment]
Hi Ankh, are you running kodi 18.x?

**Comment by dut-iptv** [comment]
OSMC still does not have a Kodi 19 version available, they expect to release a public test build in a short while if their discord is to be believed.

Leia is not supported anymore which means that you will not be able to use the addon o. Leia if providers break functionality by changing their API (as Ziggo has done after my support for Leia ended)

Please wait for OSMC to update to Kodi 19 and try again.

**Comment by Ankh-** [comment]
Okay, will wait before osmc will update to v19. Maybe change the readme that v18 and osmc isnt supported anymore?
