### ISSUE TITLE
[T-Mobile] Too many devices

### ISSUE THREAD

**Issue by Rover1NL** [dut-iptv/dut-iptv#38]
Hello,
i am an T-mobile user, and the problem with the t-mobile app is that it doesn't logoff.
for T-mobile, because you make use of the tv-anywhere app, you have a maximum of 3 logons.
so if you're app doesn't logof you cant use the tv anywhere app on an other device.

**Comment by dut-iptv** [comment]
I don't understand your issue.

Is it related to the amount of concurrent streams you can play?

Or to the amount of device you can register?

T-Mobile does not have an option to unregister devices. It will only ask you to unregister a device if you try to register a new device and already have the maximum amount of registered devices. There is no way to change this behaviour.

**Comment by Rover1NL** [comment]
Hello,

It’s the number of streams is set to maximum 3 streams bij T-Mobile.
If you log in to TV-Anywhere and there isn’t a stream left, then you can log an other device off.
With youre app thats not happening so we cant watch anything anymore via KoDi.

I hope the issue is clear now

Van: dut-iptv ***@***.***>
Verzonden: dinsdag 13 april 2021 22:14
Aan: dut-iptv/dut-iptv ***@***.***>
CC: Rover1NL ***@***.***>; Author ***@***.***>
Onderwerp: Re: [dut-iptv/dut-iptv] auto logoff for T-mobile (#38)


I don't understand your issue.

Is it related to the amount of concurrent streams you can play?

Or to the amount of device you can register?

T-Mobile does not have an option to unregister devices. It will only ask you to unregister a device if you try to register a new device and already have the maximum amount of registered devices. There is no way to change this behaviour.

**Comment by dut-iptv** [comment]
You have not given any new information and have not made any effort to clarify your issue. 

If you don't specify what you are trying to do, what does not work as you expect, what devices and applications you are trying to do this on you issue will be closed for lack of specifics and failure to follow the issue template.

**Comment by Rover1NL** [comment]
Op zijn Nederlands dan,

T-Mobile kan op maximaal 10 apparaten registreren waarvan er 3 mogen streamen.

Mijn maximaal aantal apparaten om aan te melden staat al op 10 in dit geval.

Als ik mij via "tv-anywhere" of via "t-mobiletv. nl" aanmeld kom ik op een extra pagina waar ik een ander apparaat kan verwijderen, en zodoende toch kan inloggen.
Dit laatste kan dus niet met de app voor kodi.
Deze geeft alleen de melding dat er teveel apparaten zijn aangemeld.

Sorry mijn Engels is te beperkt om dit uit te leggen.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden

________________________________

**Comment by dut-iptv** [comment]
That clears thing up.

The addon tries to replace another device automatically for you if you already have 10 registered devices.
It tries to replace a browser/PC based device but if it could not find such a device (because you only had smartphones/tablets registered for example) it gave the "Too many devices" error.

I have updated the addon to first try to replace a browser/PC based device, but if it fails in this it will ultimately replace any other device. This should solve your problem.

**Comment by Rover1NL** [comment]
Works great now thx for the update

**Comment by dut-iptv** [comment]
Good to hear.

Closing.
