### ISSUE TITLE
[Ziggo Go][1.0.0] Can't login due to an "Unexpected Error"

### ISSUE THREAD

**Issue by sankasan** [dut-iptv/dut-iptv#40]
**Describe the bug**
Logging in with a Ziggo account throws an Unexpected Error when using the Ziggo Go plugin.

**To Reproduce**
1. Go to Ziggo IPTV plugin
2. Click on Login
3. Enter Username and Password
4. See error in the screenshot.

**Expected behavior**
Login credentials to be accepted.

**Screenshots**
![IMG_20210417_152950](https://user-images.githubusercontent.com/2207658/115115116-de62f180-9f92-11eb-8e08-4530f87f79df.jpg)

**Device (please complete the following information):**
- Type: LibreElec on RaspberryPi 3
 - OS: LibreElec
 - Version [9.2.6

**Additional context**
The KPN plugin works without any issues.

**Comment by dut-iptv** [comment]
Leia is not supported anymore and Ziggo changed the API after support ended as stated in #30 #31 #32 #33 #35 #36.

Closing
