### ISSUE TITLE
[NLziet][1.1.6] Series are not showing episodes

### ISSUE THREAD

**Issue by jbouwh** [dut-iptv/dut-iptv#41]
**Describe the bug**
Series shows a non alphabetical list of available series. When a serie is selected, no episodes, but ~no items~ is shown
**To Reproduce**
1. Go to 'Series'
2. Click on 'A random serie'
3. No episodes are shown since today. In the NLziet app the episodes are available.

**Expected behavior**
The available episodes should be available for watching.

**Screenshots**
n/a

**Device (please complete the following information):**
- Type: RPI 4b
 - OS: Libreelec 9.95.1
 - Version: Kodi 19.0.0 - Matrix, build 2021-03-11

**Additional context**
This issue seems to have started since 19 april 2021. May be some API change.

**Comment by dut-iptv** [comment]
NLZiet has indeed moved from their V6 API to V7 API which introduced lots of changes to URL's and JSON output.

Will take a couple of days to sort out the changes, hampered further by the fact that I don't have a subscription right now so I can't test playback

**Comment by robje** [comment]
A +1 / me-too here.

What can be done to help fix this issue?

**Comment by dut-iptv** [comment]
1.1.7 should show the correct shows/movies etc. again.
Please test playback and report back if this works.

Please note: the "All programs/Alle programma's" menu option still does not work

**Comment by jbouwh** [comment]
Playback seems to be recovered. The all programs option seems to work here as well. Still using 1.1.6. Still need to update the plugin.

**Comment by jbouwh** [comment]
Updated manually. Series NPO is now separate from other series. Series shows no items, Series NPO populaties but does not play. Movies NPO fails with a NoneType exception on line 390. Movies (other) populates but does not play. Code needs a lot of testing.

**Comment by jbouwh** [comment]
Since Version 1.1.7 breaks the plugin and the old API is still working, please revert the code to tha last stable point. Closing this issue since the old API is working again. See https://github.com/dut-iptv/dut-iptv/issues/49 for the follow up.
