### ISSUE TITLE
[ALL][ARM64] Error installing widevine

### ISSUE THREAD

**Issue by flos06** [dut-iptv/dut-iptv#42]
**Describe the bug**
When running an addon (I've tried nlziet and videoland) I am unable to install widevine. It gives me the error arm 64 bit ondersteunt het afspelen van widevine niet. Een besturingssysteem met een 32 bit userspace is vereist.

I am running osmc matrix on a rpi 4. It has 32 bit userland. Also netflix manages to install widevine fine and works correctly. Any idea how to fix?
**To Reproduce**
1. Go to 'addon try to play something or try to install widevine'

**Expected behavior**
It should install widevine
**Screenshots**

**Device (please complete the following information):**
- Type: [e.g. Android TV Box / PC / Smartphone]
Raspberry pi 4
Osmc matrix
**Additional context**

**Comment by flos06** [comment]
Fixed it myself by forcing arch = 'armv7' in inputstream.py

**Comment by dut-iptv** [comment]
Should be fixed in 1.1.7

**Comment by flos06** [comment]
is 1.1.7 not in the repo yet? I'm not getting an update

**Comment by dut-iptv** [comment]
Sorry code was correctly modified a week ago, but forgot to change addon.xml to the new version number. 1.1.7 should be found by Kodi now.
