### ISSUE TITLE
Unable to configure PVR client with Ziggo Go

### ISSUE THREAD

**Issue by MauriceW67** [dut-iptv/dut-iptv#43]
**Describe the bug**
I can no longer get the auto configuration for the PVR Simple IPTV client to work with Ziggo Go.

I was able to do it once, but I noticed that the EPG was no longer being updated a few days ago.

I tried uninstalling and reinstalling the addon and all its dependencies and even the Simple IPTV client but nothing works.

**To Reproduce**
1. Run the Ziggo Go addon
2. Go to Settings
3. Try to start "Auto setup Kodi Language/PVR"
4. No wizard is started, only a notification is shown immediately that says "Ziggo Go Done"

**Expected behavior**
The PVR Simple IPTV client to be configured automatically again.

**Device (please complete the following information):**
- Type: Nvidia Shield Pro 2019
 - OS: Android TV 9 (Pie)

**Additional context**
Watching channels through the Ziggo Go addon itself works without issues. Only the IPTV PVR setup doesn't work.

**Comment by MauriceW67** [comment]
I fixed it by manually installing and running the "Dut-IPTV Simple IPTV Connector" from the repository.

When running this addon separately instead of from the Ziggo Go addon, the wizard starts and the IPTV client is configured successfully.

**Comment by dut-iptv** [comment]
The Auto setup Kodi Language/PVR option only automatically changes some kodi settings. It does not have any more function than that. The connector is always required to setup simple iptv and to keep the epg up to date.

Thus this is not a bug, it is intended functionality.

**Comment by oedsie** [comment]
The simple iptv connector keeps shutting my kodi down. Also using a Nvidia Shield 2019 kodi 19.3
