### ISSUE TITLE
[T-Mobile] No EPG data

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv#44]
Hi! I have an empty epg since a couple of days using t mobile. I tried to remove the epg data to import new data, but that didn't solve it.

Also ran the iptv connector again, but still the same issue..

**Comment by Pukson** [comment]
Got the same issue here. Tried reinstalling, delete old EPG data etc. But no luck. When I restart Kodi I can see at the right corner that it loods EPG data but that's it

**Comment by powermarcel10** [comment]
Thanks for the confirmation. Also T Mobile?

**Comment by Pukson** [comment]
> Thanks for the confirmation. Also T Mobile?

Yes sir

**Comment by dut-iptv** [comment]
Can confirm the issue and am looking into it

**Comment by dut-iptv** [comment]
Should be fixed. Please confirm

**Comment by powermarcel10** [comment]
I see no app update. Is this something you fixed another way? I tried to run the iptv connector again and selected T mobile, but still no data.

**Comment by dut-iptv** [comment]
There was a problem with the EPG data, which is fixed and requires no update to the addons. You should be able to see the correct data in the addon when selecting replay TV. Because of caching it can take a bit longer before you see the new data in Simple IPTV

**Comment by dut-iptv** [comment]
Can confirm that the EPG should be visible again in Simple IPTV

**Comment by powermarcel10** [comment]
Yes, sorry. It took some time, but now its working fine again. Thanks!
