### ISSUE TITLE
[Videoland][1.1.6+matrix.1] Audio crackling kodi 19

### ISSUE THREAD

**Issue by Ruudjhuu** [dut-iptv/dut-iptv#45]
**Describe the bug**
When starting video playback, the audio is crackling and popping.

**To Reproduce**
1. Setup the plugin as explained in the README
2. Start a serie or film

**Expected behavior**
Video is playing with clean clear audio.

**Device (please complete the following information):**
- Type: Raspberry pi 4 2gb
 - OS: xbian
 - Browser  don't know
 - Kodi 19.0.0 

**Additional context**
Everything is working fine except for the audio. Great job !!
Other videos and plug-ins (Netflix) are working fine with the same audio codex (ACC).

**Comment by dut-iptv** [comment]
This is probably not something I can fix as the plugin only acts as a go between to deliver the stream URL/license to Kodi + Inputstream Adaptive. My plugins are not involved in the playback itself. 

The fact that a similar codec works in another addon does not mean the plugin is to blame as the used codec is only one of the many factors that determine if playback is done in the expected way.

Have you tried if the same issue occurs on a Windows PC?
Have you tried if the same issue occurs on the latest LibreELEC beta for RPI 4?

**Comment by Ruudjhuu** [comment]
Thanks for your quick reply, I had to find some time to test different configurations.

I installed libreelec 10 beta2 on my rpi4. The videoland plugin works fine. It might be an xbian problem which i'm not going to pursue. I'll stick with libreelec.
