### ISSUE TITLE
ziggo go back to channel

### ISSUE THREAD

**Issue by dvdevil** [dut-iptv/dut-iptv#46]
Dropouts...
Hello, I have a failure when watching TV from Ziggo, it happens either after 5 minutes or after 20 minutes and after an hour of watching 4x failure.
Tested on laptop intel nuc and my pc.

**Comment by dut-iptv** [comment]
Please follow the issue template for your title and issue description. 

Issue should be fixed in 1.1.7, probably related to a change in the Ziggo API or Inputstream Adaptive
