### ISSUE TITLE
Ziggo shows ~No items~

### ISSUE THREAD

**Issue by epistrophy42** [dut-iptv/dut-iptv#48]
**Describe the bug**
Just installed the plugin and added my Ziggo username and password: login is succesful. But when I go to Live TV or Replay TV, I see no channels, only ~ No Items ~. When I do NOT login and start the addon unauthenticated, i see the channels appear but I can't open because the credtials are missing. 

**Expected behavior**
I expect to see the channels of Ziggo.

**Screenshots**

**Device (please complete the following information):**
- Odroid N2+
- OS: CoreELEC, Kodi Leia 18.9
- Widevine CDM is installed
- Installed Addons: Dut-IPTV Proxy (Anon - 1.0.4), Dut-IPTV Simple IPTV Connector (Anon 1.0.0) and Dutch IPTV Repository (Anon 1.1.0)

**Additional context**

**Comment by atreyuhere** [comment]
These are older build versions on v.18, which is no longer supported. Since you are running N2+, you could  update to the current stable v19, install latest versions  and try again.

**Comment by epistrophy42** [comment]
I downloaded and installed CoreELEC-Amlogic-ng.arm-19.1-Matrix_rc4-Odroid_N2.img on an SD-card and put it in the Odroid-N2+.

If I follow the manual and only install the repository.anon.iptv ZIP file, then I cannot configure this Addon: something is still missing.

But only if I also manually install zip-files script.module.fuzzywuzzy-0.17.0 + matrix.1, plugin.video.ziggo-1.1.6 + matrix.1 and plugin.executable.dutiptv-1.1.6 + matrix.1, then I can configure the Ziggo Addon, enter my username and password and I come to Live TV and Replay TV.

So its working: and that's great!

Thank you so much, Mike
