### ISSUE TITLE
[NLziet][1.1.7] Videos with v7 API not playing

### ISSUE THREAD

**Issue by jbouwh** [dut-iptv/dut-iptv#49]
The 1.1.7 update breaks playing the video's of series (NPO or other).

**Expected behavior**
I expect the video to play. With 1.1.6 Series videos still play

**Device (please complete the following information):**
- Type: Any
 - OS: Android/Linux/Windows

**Additional context**
Bug in new code

**Comment by jbouwh** [comment]
Perhaps it is a good idea to revert to the previous stable code with the old API and start a beta release with the new code since a bugfix is not needed any more.

**Comment by dut-iptv** [comment]
Playback using V7 was implemented in 1.1.8
