### ISSUE TITLE
NLZIET 1.1.7+Matrix.1 - Rewind live video: Audio plays but video hangs

### ISSUE THREAD

**Issue by LaTrappe** [dut-iptv/dut-iptv#50]
**Describe the bug**
On my Nvidia Shield, when rewinding (or start from start) audio plays correctly but video hangs. It just shows a frame every 30 sec. or so. On the VOD (or watch later) this issue does not occur. 

**To Reproduce**
1. Open a live stream (NPO or other makes no difference)
2. Skip a few minutes back on the time bar
3. Audio moves to the right timestamp but video hangs (on the rewind time) but 'frame rate' drops to 1x 20 sec.

**Expected behavior**
Smooth playback. As far i remember i did not have this issue on my previous NUC

**Device (please complete the following information):**
- Android TV ( 9)
- Nvidia Shield (8.2.2) 
- Kodi 19

Thanks for having a look at this.

**Comment by dut-iptv** [comment]
This should not be an issue in 1.1.8
