### ISSUE TITLE
[NLziet][1.1.7] All programs doesn't show any items

### ISSUE THREAD

**Issue by nazegnl** [dut-iptv/dut-iptv#51]
**Describe the bug**
When browsing to a running program on tv regardless of the station they all show ~ no items~ placeholder.

**To Reproduce**
1. Go to 'All programs'
2. Go to 'Titles with w'
3. Search for 'Wordt u al geholpen?'
4. See the '~no items~' placeholder

**Expected behavior**
A list with seasons or episodes for that show.

**Comment by dut-iptv** [comment]
The V7 api does not seem to implement the endpoint that was used to create this view.
The menu option has been removed in 1.1.8.
