### ISSUE TITLE
[**NLZIET**][**1.1.8 MATRIX**] **Unable to play MOVIES and more issues**

### ISSUE THREAD

**Issue by Nigel1992** [dut-iptv/dut-iptv#53]
**Describe the bug**
1. Unable to play any movie located in Movies.
Certain movies try to play, but give an error while others simply don't attempt to play at all.
NPO Movies all work fine.

2. NPO Series gives an error upon opening the menu NPO Series.
3. Series work but when I click on next page, it shows an error with API.

**To Reproduce**
See above details.

**Device (please complete the following information):**
RPI 3B+
Kodi (19.1 (19.1.0) Git:19.1-Matrix > LibreELEC (community): nightly-20210512-39d1620 10.0

**Additional context**
[kodi.log](https://github.com/dut-iptv/dut-iptv/files/6534942/kodi.log)

**Comment by flos06** [comment]
I have the same issues.

**Comment by flos06** [comment]
Any ideas for a fix?

**Comment by dut-iptv** [comment]
Sorry for the long delay. No free time and issues with my development environment.

Issue should be fixed in 1.2.1
