### ISSUE TITLE
Epg update not working anymore

### ISSUE THREAD

**Issue by mrblond18** [dut-iptv/dut-iptv#54]
I have mapped several channels from both KPN and Ziggo to the Simple IPTV addon. This used to work fine, including the EPG. I see now that the epg is not filled for quite a few channels and for the ones that still show epg (like NPO 1) it is only until tomorrow (until Saturday around noon).

I investigated the epg.xml file in .kodi/userdata/addon_data/plugin.executable.dutiptv. 
I found out that e.g. for NPO 1 (channel 18 in the epg) the guide start and ends with:
`<programme channel="18" start="20210528225000 +0000" stop="20210528235000 +0000" catchup-id="876084215">`
...
`<programme channel="148" start="20210612123000 +0000" stop="20210612131000 +0000" catchup-id="876309117">`

For 24 kitchen (channel 175):
`<programme channel="175" start="20210528220700 +0000" stop="20210528222900 +0000" catchup-id="876116542">`
...
`<programme channel="175" start="20210610220000 +0000" stop="20210611220000 +0000" catchup-id="876302799">`
So this channel does not show any info.

The epg.xml file gets nicely updated each day (looking at the file properties), but does not contain any new programs. I have confirmed this on both ubuntu and OSX. Both the KPN and Ziggo channels do not get updated program info.

I would gladly supply more info, but do not know how to further debug...

edit: just tried it on a fresh windows 10 kodi install, same issue

**Comment by dut-iptv** [comment]
Server crash caused the EPG updater to fail. Should be fixed now, but because of caching it could take up to 12 hours to rectify itself on your devices.

**Comment by mrblond18** [comment]
Thanks, works fine again!
