### ISSUE TITLE
F1TV - everything works, except live programs.

### ISSUE THREAD

**Issue by RobOo-Github** [dut-iptv/dut-iptv#55]
I use LibreELEC (Matrix 19.1) 10.0 BETA3 , your repository (latest version) F1TV plugin. 
Everything works nicely, watching all the shows, on each channel: just fine.
Except when I watch a live broadcast, like a live race, then it fails to start: 

![error](https://user-images.githubusercontent.com/65445647/122737657-9063b600-d281-11eb-8993-35a9deb72fae.jpg)

Am I doing something wrong, or is this a bug?
All the best, Rob

**Comment by dut-iptv** [comment]
Bugs in Live listing and playback should (finally) be fixed in 1.2.1
