### ISSUE TITLE
T-Mobile TV doesn’t work anymore

### ISSUE THREAD

**Issue by Pukson** [dut-iptv/dut-iptv#57]
Issue:

channels start fine and play for like 10 seconds after that it will stutter and then hang. Looks like buffering but it isn’t, how long I wait it won’t play again until I select the channel again. Then it does the same loop as stated above. Didn’t had that issue a week ago. Internet is fine here.

ive tried to reinstall the addon and kodi but didn’t solve the issue

**Comment by Pukson** [comment]
Don’t have a lot of knowledge about coding. But isn’t the issue caused by importing proxy version 1.1.7 as I see with latest change? 

While the change before that it goes from 1.1.7 to 1.1.9?

https://github.com/dut-iptv/dut-iptv/commit/c9dfc611da030014b84d48f928b598b626cdcde0

**Comment by dut-iptv** [comment]
A change to the T-mobile addon manifest parameters caused this problem. This change has been reverted in 1.2.0.

> Don’t have a lot of knowledge about coding. But isn’t the issue caused by importing proxy version 1.1.7 as I see with latest change?

No
