### ISSUE TITLE
Epg update not working anymore (again)

### ISSUE THREAD

**Issue by mrblond18** [dut-iptv/dut-iptv#58]
The EPG is not updated anymore. Looks like the same as:
issue #54 

NPO1 has epg info from 2021-07-02 until 2021-07-17

Is it possible your internal epg-grabber is not running anymore?

**Comment by atreyuhere** [comment]
Might be a good idea to use the issue template when reporting.
Don't know which provider you are using, Ziggo epg is working normally here.

**Comment by mrblond18** [comment]
> Might be a good idea to use the issue template when reporting.
> Don't know which provider you are using, Ziggo epg is working normally here.

Ziggo has the exact same problem. You might have EPG for now, but it will not extend beyond tomorrow... Normally it has info for over a week. Further, you would inspect the xmltv file, it will have info dating back to july 2nd, where it will normally only have info for a day back. This indicates the backend of the plugin is not getting updated with epg (for all plugins/providers)

**Comment by dut-iptv** [comment]
It's a problem of the dut-epg repository (where the EPG lives), but I don't accept issues there. So posting it here is fine. Using the template does help in formulating your issue in a standardized way and is the preferred way.

The server that creates the EPG was reinstalled en reconfigured last week which seems to have caused some trouble for the EPG. 

Should be fixed but will take a while to repopulate completely (especially for Ziggo)

**Comment by mrblond18** [comment]
> It's a problem of the dut-epg repository (where the EPG lives), but I don't accept issues there. So posting it here is fine. Using the template does help in formulating your issue in a standardized way and is the preferred way.
> 
> The server that creates the EPG was reinstalled en reconfigured last week which seems to have caused some trouble for the EPG.
> 
> Should be fixed but will take a while to repopulate completely (especially for Ziggo)

works again! Thanks
