### ISSUE TITLE
[NLziet][1.2.4] Videos and live tv not playing

### ISSUE THREAD

**Issue by jbouwh** [dut-iptv/dut-iptv#62]
**Describe the bug**
NLziet not playing after upgrade. Widevine works ok with Netflix, but not with NLziet.

**To Reproduce**
Install NLziet app libreelec 10.0.0 arch RPI4.arm 64 bit

Install the plugin
1. Login
2. Open live tv of a video
3. Click olay
4. See error. Item cannot be played

**Expected behavior**
Video should start

**Screenshots**

**Device (please complete the following information):**
- Type: [e.g. Android TV Box / PC / Smartphone] rpi4
 - OS: [e.g. iOS] libreelec 10.0.0 on rpi4 2 gb
 - Version [e.g. 22] 1.2.4

**Additional context**

**Comment by jbouwh** [comment]
Solved it by reinstalling widevine using the input stream plugin. The menu lotion to install widevine does not work.

**Comment by dut-iptv** [comment]
Your issue was probably related to the new Widevine update. Good to hear it is already fixed.

The menu item will be modified or removed in the near future, it was not yet modified after the inclusion of inputstream helper recently to take care of Widevine updates.
