### ISSUE TITLE
Could not connect to repository

### ISSUE THREAD

**Issue by dannybloe** [dut-iptv/dut-iptv#71]
I followed the instructions, downloaded the zip file and then chose install from zip. That worked and D-IPTV was nicely listed as an add-on repo when I chose Install from repository. However, as soon as I select that repo Kodi says Could not connect to repository. 

Using Kodi 18.9 on LibreELEC 9.2.8 running on a Pi3. 

Am I doing something wrong here?

**Comment by scriptmelvin** [comment]
Your Kodi version is too low. You need >= 19. Just happened to me, too, on Kodi 18. Upgraded to 19, works now.

**Comment by dut-iptv** [comment]
Please upgrade to LibreELEC 10.0.

Kodi 18 is not supported.

**Comment by dannybloe** [comment]
Mm that doesn’t work on a Pi3. It would help to mention this in the readme that this requirement is there. Could have saved me a couple of hours trying to get it to work.

**Comment by dut-iptv** [comment]
It is in the readme of the Repo and every add-ons under Required

**Comment by dannybloe** [comment]
🤦‍♂️  doh
