### ISSUE TITLE
[Videoland ADDON] [1.2.5+matrix.1] Inputstreamhelper "ModuleNotFound" Error and Fix

### ISSUE THREAD

**Issue by hagst** [dut-iptv/dut-iptv#72]
There is a PR made to fix this problem. 
But this PR is made in "dut-iptv /dut-iptv.github.io" and not in "dut-iptv /dut-iptv". 
Link to PR: https://github.com/dut-iptv/dut-iptv.github.io/pull/64

Perhaps you could use this solution for other users with the same problem.

**Comment by dut-iptv** [comment]
Tnx for reporting. Videoland was the only addon where I forgot to add the inputstream helper requirement in the addon.xml. Fixed in 1.2.6
