### ISSUE TITLE
[NLziet] Add profiles and watchlist support

### ISSUE THREAD

**Issue by djdirty60** [dut-iptv/dut-iptv#80]
Good day,
 
Is it maybe possible to add the watchlist function to the nlziet addon?  

thanks in advance

**Comment by dut-iptv** [comment]
It has been on the Wanted features (#2) list for almost a year, but have not had the time/motivation to tackle it.

I'm currently working on implementing a few similar features into the Videoland addon and hopefully can implement these features including watchlist support easily in NLZiet after this is done

**Comment by dut-iptv** [comment]
I will also add profile support to this issue.

It was recently added by NLZiet and is pretty essential if we are to correctly implement Watchlists / Continue watching support.

**Comment by djdirty60** [comment]
Oke thnx

**Comment by dut-iptv** [comment]
NLZiet version 1.4.0 with support for profiles, watchlist and library integration is now available in the **beta repository** .
Bugs are very likely.

**Comment by dut-iptv** [comment]
NLZiet 1.4.2 with support for profiles and watchlists is released in the main repo
