### ISSUE TITLE
[Videoland / NLZiet] Library integration

### ISSUE THREAD

**Issue by djdirty60** [dut-iptv/dut-iptv#84]
Good day,

Is it possible that the mark viewed function can also be placed on the seasons folders from videoland and nlziet?  You can now only mark each episode as watched.  Will be useful if you can do a whole season at once.

 thanks in advance

**Comment by dut-iptv** [comment]
By default Kodi allows marking videos/files as watched but not directories. This is why you can mark episodes, but not seasons. 

This behaviour can be changed by the addon, but I only really see the added value of this if I first implement is a library integration (which gives you the option to show series progression, new episode listing, etc). 

If I implement a library integration you can mark series, seasons, episodes as watched there without any custom (and probably crappy/hacky) code.

Library integration is already on the wanted features list (for Videoland and maybe NLZiet)

**Comment by djdirty60** [comment]
Oke thnx

**Comment by dut-iptv** [comment]
The library integration for Videoland is done and implemented in 1.3.2 (now available)
In the menu go to settings and select "Setup Library Integration" and follow the prompts.

You can choose to include all available movies and/or shows in your library (NOTE: approx. 1200 movies and 1000 shows) or only include movies and/or shows on your watchlist. You can also choose to in/exclude kids shows/movies.

The addon tries to retrieve as much information as possible from the addons own information sources and tries to not hit Videoland servers. Kodi will only query Videoland for information on the shows on your watchlist.

New movies, shows and episodes will appear in your library with a maxmimum delay of 24 hours.
Shows and episodes for shows on your watchlist will appear within an hour of release.

Please test and report any issues here

**Comment by djdirty60** [comment]
![16393439067183111697537563998084](https://user-images.githubusercontent.com/13561831/145729894-ec1ba13d-7619-4d8a-9881-9996aaee6357.jpg)

**Comment by dut-iptv** [comment]
Your error is the result of old cache. Please clear the cache directory in your userdata\addon_data\plugin.video.videoland directory or wait for the cache to expire (12 hours).

A future version will include auto clean of cache/tmp directory on new versions to remedy this.

**Comment by djdirty60** [comment]
Error Type: <class 'KeyError'> Error Contents: 'description' Traceback (most recent call last): File "/storage/.kodi/addons/plugin.video.videoland/service.py", line 2, in <module> main() File "/storage/.kodi/addons/plugin.video.videoland/resources/lib/service.py", line 27, in main update_library() File "/storage/.kodi/addons/plugin.video.videoland/resources/lib/service.py", line 101, in update_library result = create_stream(type, 'shows', librarysettings['library_shows'], skiplist2) File "/storage/.kodi/addons/plugin.video.videoland/resources/lib/service.py", line 261, in create_stream episodes[row2['ref']]['description'] = row2['description'] KeyError: 'description' -->End of Python script error report<--

**Comment by dut-iptv** [comment]
It turns out that there are a lot of edge cases in the Videoland Library (especially in the TV series).

Think fields that always exist, except in one or two cases.
Think fields that are always numbers, except in a couple of cases where they are a alphanumeric string.

The addon stumbled over these edge cases and spit out errors when encountering them.

I did not test the entire library of TV series before, but have done so now with the latest version.

1.3.4 should not give any more errors

**Comment by djdirty60** [comment]
For now it works perfectly

**Comment by djdirty60** [comment]
For gtst there is a problem, because the season maps are put in a year map the episodes don't match the episode number and text anymore, is it possible that that can be changed?

**Comment by dut-iptv** [comment]
GTST again is one of those difficult edge cases where the season is not supplied as a number (2021 for the entire season) but as a string (Voorjaar/Najaar 2021). Because currently all text is stripped from the season(number) both are seen as just 2021.

I am working on a solution but this is not an easy fix

**Comment by dut-iptv** [comment]
1.3.5 is in the repo, please let me know if this solves your issue

**Comment by djdirty60** [comment]
> 1.3.5 is in the repo, please let me know if this solves your issue

I think it will work like this yes, all streams match the data.  So for now it works as it should.

Top job done. 
Hopefully it can also be done with NLZiet.

✌

**Comment by dut-iptv** [comment]
NLZiet version 1.4.0 with support for profiles, watchlist and library integration is now available in the **beta repository** .
Bugs are very likely.

**Comment by djdirty60** [comment]
> 

Thanks will test it

**Comment by djdirty60** [comment]
There is an error in the npo part of nlziet, the .nfo files are placed incorrectly.  Episodes are correct, only the .nfo are reversed, 1 at 10, 2 at 9 etc etc
![16400219757646449190655222391125](https://user-images.githubusercontent.com/13561831/146809240-2e633ee4-c479-4748-a9db-bb79694921a2.jpg)

**Comment by dut-iptv** [comment]
I had to reverse the order on my test show (10 jaar Grenzeloos Verliefd) to get it right, but apparently other shows don't need to be reversed. This should be fixed with 1.4.1, which is in the beta repo now.

**Comment by dut-iptv** [comment]
1.4.2 including library integration for NLZiet and Videoland is released in the main repo.
