### ISSUE TITLE
 [F1 TV][1.2.11] Abu Dhabi content is missing

### ISSUE THREAD

**Issue by doormalena** [dut-iptv/dut-iptv#85]
**Describe the bug**
All material for this weekends Abu Dhabi is missing.

**To Reproduce**
1. Start add-on
2. Open 2021 Season

**Expected behavior**
All videos for race Abu Dhabi are listed.

**Screenshots**
![IMG_5373](https://user-images.githubusercontent.com/8328876/145631549-a2c32b4f-ba17-4e2d-86e7-6dbe4e18c6a2.jpg)

Device (please complete the following information):

-  Type: PC
-  OS: Windows 10 (latest patch level)
-  Browser: Not relevant
-  Version: Kodi Matrix 19.3 (was also an issue with earlier versions of Kodi)

**Additional context**
Reset the add-on and re-entering login credentials did not make a difference.

Using [Race Control](https://github.com/robvdpol/RaceControl) standalone app, and the official F1 TV app do show the Abu Dhabi content.

**Comment by dut-iptv** [comment]
Fixed in 1.3.1

**Comment by doormalena** [comment]
Works now. Cool. Thanks!
