### ISSUE TITLE
[Dut-IPTV Simple IPTV Connector] Error during configuration

### ISSUE THREAD

**Issue by Pukson** [dut-iptv/dut-iptv#89]
So today I did a clean install of Kodi and installed Dut IPTV. The channels all work great, but when I try to get the Simple TV connector to work, it fails. Installation went fine but in the setup I get an unexpected error. 

TypeError: NoneType object is not iterable.

![PXL_20211216_114901689](https://user-images.githubusercontent.com/13370171/146366425-a14ba61a-a380-48b5-8fee-9ecfcd795635.jpg)

**Comment by Mislancer** [comment]
Hello,

Same problem, installing NLZiet, kind regards.

![WhatsApp Image 2021-12-16 at 17 14 44](https://user-images.githubusercontent.com/3470747/146408561-5d80b65b-5500-4599-9c8a-4f9473c01b41.jpeg)

**Comment by dut-iptv** [comment]
Bug introduced during recent general code cleanup/improvements.
Fixed in 1.3.6 of the connector, now in the repo

**Comment by Mislancer** [comment]
Thanks, for the fast reply, first part is working again. Accept at the and when trying to configure i'm getting a error.

![WhatsApp Image 2021-12-16 at 17 59 11](https://user-images.githubusercontent.com/3470747/146415690-c6d9a5f3-6844-420f-af7d-9af0c29a05f6.jpeg)

![WhatsApp Image 2021-12-16 at 17 59 11(1)](https://user-images.githubusercontent.com/3470747/146415767-42bd3c00-995f-4997-9c15-4ad09a6ee3c9.jpeg)

**Comment by dut-iptv** [comment]
1.3.7 should fix this second error

**Comment by Mislancer** [comment]
Thank you again it seems no error any more, just an empty epg. Restarted Libreelec 10.0.1 but doesn't make any diference. It's not loading any epg input

![IMG_20211216_202948](https://user-images.githubusercontent.com/3470747/146436241-96f0f69e-7546-43bf-8016-d402fe3b367a.jpg)

**Comment by Mislancer** [comment]
After running configurationele of dutiptv i het the following log.

![IMG_20211216_203320](https://user-images.githubusercontent.com/3470747/146437245-697a1d8f-5db3-4107-943d-8e7ec019028c.jpg)

![IMG_20211216_203547](https://user-images.githubusercontent.com/3470747/146437264-f4356f30-672e-4f0f-a76b-f1ce6ce29f9f.jpg)

**Comment by dut-iptv** [comment]
Third problem should be fixed in 1.3.8

**Comment by Mislancer** [comment]
Doesn't seem to work, i still get the same error.

**Comment by dut-iptv** [comment]
The last log you posted are irrelevant/not errors. Reconfigure the Dut-IPTV connector and reboot Kodi

**Comment by Mislancer** [comment]
Strange, I did a reconfigure and a restart but still an empty EPG. NLziet is working. Is there something else I can do?

**Comment by dut-iptv** [comment]
You are sure you are on version 1.3.8? Kodi caches repo info and you only get updates immediately when searching for updates manually.
You can also try removing the addon userdata from your Kodi userdata directory (plugin.executable.dutiptv)

**Comment by Mislancer** [comment]
Yes i'm using 1.3.8. I will look in to it later this day. I Have to work first. I will let you know if it works.

**Comment by Mislancer** [comment]
Yes it's working again, Thank you for all the hard work
