### ISSUE TITLE
Not able to add TVE

### ISSUE THREAD

**Issue by MartySouth** [dut-iptv/dut-iptv#91]
Not able to add Spanish TV channel TVE to TV Group via "Dut-IPTV Simple IPTV Connector Addon" from "Ziggo Live TV" on "Amazon Full HD Fire TV Stick International Version" on Kodi 19.3

It's green on the list of "Ziggo Live TV" but it doesn't show up in the IPTV Simple PVR Addon.

**Comment by dut-iptv** [comment]
You will be able to add TVE through the Dut-IPTV Simple IPTV Connector within the next 12 hours (because of caching).

If you want to add it immediatly you can clear your cache and tmp directories in the Kodi userdata/addon_data/plugin.executable.dutiptv directory.
