### ISSUE TITLE
ziggo SSL error

### ISSUE THREAD

**Issue by anno006** [dut-iptv/dut-iptv#92]
**Describe the bug**
When live or replay next error:
Requests.exceptions.SSLError:HTTPSConnectionPool(host='obo-prod.oesp.ziggogo.tv',port=443): Max retries exceeded with url: /oesp/v4/NL/nld/web/settopboxes/profile (Caused by SSLError(SSLError(1, '[SSL:WRONG_VERSION_NUMBER] wrong version number (_ssl.c:xxxx)'))) etc.

**To Reproduce**
use this app?!

**Expected behavior**
Working?!

**Comment by dut-iptv** [comment]
Your issue will only be taken in consideration if you follow the issue template. At the very least supply information about your environment, os, device etc. 

As you seem to be the only one with this issue it seems most likely that this issue arises from some configuration issue with your network.

**Comment by anno006** [comment]
sure, your plugin is the only one that gives problems, here. so it must be you app!!! 

First tell something about the error before we propperbly can talk about my os where kodi is running off. and i did follow the gidelines, i give the information needid!!

**Comment by anno006** [comment]
i did find vthe problem, you attitude and you crappy useless and shit manual. $#%(@% you and goodbye
