### ISSUE TITLE
Ziggo GO Login Error

### ISSUE THREAD

**Issue by MartySouth** [dut-iptv/dut-iptv#93]
I had to re-login the Ziggo GO Video Addon on "Amazon Full HD Fire TV Stick International Version" on Kodi 19.3 after a cold boot as when I tried to watch any channel it gave me a key access error.

Ziggo GO was also orange on the list of the IPTV Simple PVR Addon.

**Comment by dut-iptv** [comment]
Fixed in 1.4.2
