### ISSUE TITLE
Epg update not working anymore (again x2)

### ISSUE THREAD

**Issue by MartySouth** [dut-iptv/dut-iptv#94]
Ziggo Go EPG is empty since 15:00 today.

**Comment by dut-iptv** [comment]
I will look into it. Note that this is not a general failure of the EPG updater (which have occured in the past) but specific to Ziggo and specific to the EPG of today and is a result of the gymnastics that need to be done to download the entire Ziggo EPG while preventing duplicates and removing old entries.

Please note: No matter the issue, failure to adhere to the issue guidelines will result in immediate issue closure in the near future.

**Comment by MartySouth** [comment]
EPG is filled again

**Comment by dut-iptv** [comment]
No work has been done to fix this issue as of yet so this issue can and will pop up again untill I have had time to look into it.

**Comment by dut-iptv** [comment]
Further checks have been put in place to prevent repeat of this problem. In the last two months I've not seen it come back since. If it resurfaces please reopen this issue.
