### ISSUE TITLE
[NLZIET][1.4.2] missing series in library

### ISSUE THREAD

**Issue by djdirty60** [dut-iptv/dut-iptv#95]
Good day,

I'm missing a few series in my kodi library from NLZiet, when I go to the original NLZiet app I have 17 series there, also in the addon library, but 12 in the kodi library.  So I guess not all series are updated to the library, or the data in the addon isn't visible.

I look forward to hearing from you, thanks in advance for all the hard work

**Comment by dut-iptv** [comment]
What series are not showing?
Have you waited more than an hour between changing your watchlist and checking your library?
What are the contents of your userdata/addon_data/pluging.video.nlziet/shows directory? Do the missing shows turn up there and are there season directories, nfo's and .strm files?

Please note: No matter the issue, failure to adhere to the issue guidelines will result in immediate issue closure in the near future.

**Comment by djdirty60** [comment]
> What series are not showing? Have you waited more than an hour between changing your watchlist and checking your library? What are the contents of your userdata/addon_data/pluging.video.nlziet/shows directory? Do the missing shows turn up there and are there season directories, nfo's and .strm files?
> 
> Please note: No matter the issue, failure to adhere to the issue guidelines will result in immediate issue closure in the near future.

Yes, it took a few days, so it's not that.

Here is the show map.
![16412429857413160855742019078493](https://user-images.githubusercontent.com/13561831/147978905-68bb9e06-9ffd-4bad-9f4b-2486e6c9e0a6.jpg)

And here's the addon folder.
![16412430465515717825336298871783](https://user-images.githubusercontent.com/13561831/147979003-75fc5e9f-6de2-4f35-8074-003b1eadff32.jpg)
![16412430775382836273062451646872](https://user-images.githubusercontent.com/13561831/147979045-9010a39c-b500-4e62-b9bc-23e16dd0a76e.jpg)

**Comment by dut-iptv** [comment]
Issue should be resolved on the EPG side. Will take about 24 to 48 hours to propagate to your system because of caching.

No update to the addon necessary.

**Comment by djdirty60** [comment]
Okay thanks,

 Will wait a while

**Comment by djdirty60** [comment]
Nog een klein vraagje, zal het mogelijk zijn dat net als bij videoland als je iets bekeken hebt dat dat ook bij NLZiet zelf als bekeken wordt gemarkeerd?
