### ISSUE TITLE
[NLZiet + KPN iTV + Videoland][1.4.2+matrix.1] stuttering and buffering constantly

### ISSUE THREAD

**Issue by Nigel1992** [dut-iptv/dut-iptv#96]
**Describe the bug**
Whenever I try to play something, it keeps on buffering.
This is for both Live and VOD.
It seems to only occur when the video is 1080p because 720p (older videos such as Dream School: Season 1 on NLZiet) plays fine.

**To Reproduce**
See above

**Expected behavior**
Play videos flawlessly.

**Screenshots**
N/A

**Device (please complete the following information):**
Raspberry Pi 3B+ Rev 1.2
LibreELEC 11
Kodi 20.0-ALPHA1 (19.90.101)
NLZiet/KPN iTV/Videoland 1.4.2+matrix.1

**Additional context**
N/A

**Comment by dut-iptv** [comment]
This is not an addon issue. You are using a highly experimental build on an unsupported platform and alpha version of Kodi/LibreELEC. 

Hardware decoding is probably not supported in your LibreELEC build and the RPI 3 is not powerful enough to Software decode H264 above 1080P. You can expect the same results in Netflix, Disney+ etc. 

You should follow the LibreELEC developers/developments on their forums for news on HW decoding in these builds and try again when development is further along.

**Comment by Nigel1992** [comment]
@dut-iptv 

I know I am running a test version but it was working fine on my stable Leia instance until a few days ago.
That version is getting the exact same issue.
I know Leia is not supported but if it plays 720p, why is 1080p acting the exact same way the test version does ?

**Comment by dut-iptv** [comment]
Decoding 1080P requires more processing power than 720P. The Rpi 3 probably only has enough power to decode most 1080P content when it is using HW acceleration. What content it is able to decode is dependent on many different factors such as video and audio encoding, bandwidth and resolution.

DRM can also be a factor, which might explain a difference between public and commercial broadcast at KPN.

It is important to realize that in regard to playback in Kodi all addons for major streaming services (including Netflix, Disney+ etc) and my own addons only supply Kodi and another addon (Inputstream Adaptive) with the right URLs and authentiction

**Comment by Nigel1992** [comment]
> Decoding 1080P requires more processing power than 720P. The Rpi 3 probably only has enough power to decode most 1080P content when it is using HW acceleration. What content it is able to (HW) decode is dependent on many different factors such as video and audio encoding, bandwidth and resolution.
> 
> DRM can also be a factor, which might explain a difference between public and commercial broadcast at KPN.
> 
> It is important to realize that in regard to playback in Kodi all addons for major streaming services (including Netflix, Disney+ etc) and my own addons only supply Kodi and another addon (Inputstream Adaptive) with the right URLs and authentication to download/stream and start playback of the requested content. The addon itself has no part in playback after supplying this information and as such is not a factor in buffering issues.

How can I downgrade widevine ?
Jus to test if it’s a DRM issue

**Comment by dut-iptv** [comment]
You can't basically, because Widevine launched an update recently because of private key leaks and advised content creators to invalidate old versions.

I also don't expect it to matter because it is more a factor of using DRM of not using DRM that can have an impact on playback, not which Widevine version you use.

**Comment by Nigel1992** [comment]
@dut-iptv 

I just restored an old backup of your Leia version of NLZiet and its having the exact same issue.
My Leia version is stable so it must be DRM related. What now ?
I’m not asking for Leia support just DRM.

**Comment by dut-iptv** [comment]
There is no solution. Wait for a decent Rpi 3 build of libreelec or osmc for matrix/nexus with hardware acceleration of change to a better supported and more powerful platform such as Rpi 4 or Amlogic/CoreELEC.

**Comment by Nigel1992** [comment]
@dut-iptv 
Found a guy with the exact same issue but he is running a Vero 4K+
It working perfect on my Windows 10 machine so perhaps it’s a Linux DRM issue ?

**Comment by dut-iptv** [comment]
The first hit on Google when you lookup vero 4k netflix states that both pi 2/3 and vero 4k are not powerful enough to decode 1080p widevine content. I don't own any of these devices so can't comment on my own experience with them.

You can disable "force maximum quality" in my addons (not sure if these where introduced in Leia build) and enable "manual stream selection" or set "max bandwidth" in Inputstream adaptive and select a lower quality (eg 720p) stream.

**Comment by Nigel1992** [comment]
@dut-iptv 
I have been using your addons for a year now on my Pi 3B+ and they always worked perfectly.
Both on Leia and Matrix.
My Pi is clearly powerful enough so it somehow must be DRM.
I’ll try your suggested steps.

**Comment by dut-iptv** [comment]
Perhaps considering all this the Widevine version does play a part, but there is no point in further debating or debugging as old Widevine versions are no longer usable (again not influenced by the addons but by Google/Widevine/Content providers)

**Comment by Nigel1992** [comment]
> Perhaps considering all this the Widevine version does play a part, but there is no point in further debating or debugging as old Widevine versions are no longer usable (again not influenced by the addons but by Google/Widevine/Content providers)

After multiple reinstalls of the latest Widevine for Linux Arm its working now.
It sometimes still has the issue but when I reopen the stream it’s fixed. Very odd but works again!

**Comment by Nigel1992** [comment]
Seems to be working perfectly now after downgrading InputStream Adaptive. :)

**Comment by Nigel1992** [comment]
@dut-iptv 
If someone ever has this same buffering issue and is on Kodi 19 or higher, he should try to disable “http2” in advancedsettingx.xml by adding:

< network >
< disablehttp2 > true < /disablehttp2 >
< /network >

This fix has been confirmed on another forum.

**Comment by marten-z** [comment]
I had a similar issue. Streams did still start, but started buffering almost immediately, then run for like 30 seconds or so, then started buffering again... and so on. In my case, this started after updating to the latest Widevine CDM version.

Raspberry Pi 3B
LibreELEC 9.2.8
Kodi 18.9 Leia

I was able to get rid of the issue by:
1. Navigating to the Kodi Inputstream Helper addon 
2. Hit the **Remove Widevine CDM** option _(removes the current Widevine CDM)_
3. Hit the **Restore Widevine CDM** option
4. Choose latest version from backup (version **4.10.2252.5** from Chrome OS FIEVEL image version **14150.87.0**)
